erDiagram
    USERS {
        int userId
        string username
        string password
        string email
        string firstName
        string lastName
        string address
    }

    BUYER {
        int buyerId
        bool isBuyer
    }

    SELLER {
        int sellerId
        bool isSeller
    }

    ITEMS {
        int itemId
        string itemName
        string itemDescription
        bool isClosed
        bool imagePath
    }

    CATEGORIES {
        int categoryId
        string name
        string description
    }

    BIDS {
        float bidPrice
        date bidDate
        bool isWinner
        bool isHighest
    }

    AUCTIONS {
        float reservePrice
        float startPrice
        date startDate
        date endDate
        string auctionResult
    }

    NOTIFICATIONS {
        int notificationId
        string subject
        string message
    }
    
    NOTIFICATIONS2 {
        date notificationDate
        bool isRead
    }
    RATINGS {
        int itemId
        int rating
        string comment
    }

